Cloud bastion
Otus-DevOps-2021-11/akepman_infra pull request #2
Opened 2021-12-19 06:47 UTC by akepman

cloud-bastion  fin

2021-12-20 12:01 UTC, mrgreyves approved these changes
Здравствуйте!)
Формально у вас есть описание, но оно никак не отображает проделанную работу
Не забывайте про то что стоит вести как описание в пуллреквестах, так и в ридми =)

2021-12-30 18:43 UTC, akepman commented
Подправил описание readme

2021-12-30 18:44 UTC, akepman commented
А что означает Closed?

2022-01-04 10:24 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Стоит поправить ридми и все места куда попадают символы в непонятной кодировке
Для редактирования рекомендую использовать Microsoft Visual Studio Code

2022-01-04 10:24 UTC, mrgreyves commented on README.md
> +## ��� ��������� �����������������:
Ух тыж ё-мое 0_о
У вас тут явно какие странные проблемы с кодировкой

2022-01-04 13:59 UTC, akepman commented
Подправил кодировки везде где нужно сделал UTF-8

2022-01-05 12:10 UTC, mrgreyves approved these changes
Здравствуйте!)
Хорошо что изменили кодировку
Видимо на момент повторных тестов ваша инфраструктура была уже выключена
В остальном все выглядит корректно, дз принимаю =)

2022-01-25 19:42 UTC, merged