Play travis
Otus-DevOps-2021-11/akepman_infra pull request #3
Opened 2021-12-19 10:37 UTC by akepman

+

2021-12-20 12:07 UTC, mrgreyves requested changes
Здравствуйте!)
Оставил вам комментарий к файлу
ДЗ возвращаю на доработку

2021-12-20 12:07 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Вот сюда смотрим внимательно и правим этот файлик =)

2021-12-30 07:33 UTC, akepman commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
так, подправил, Action прошел нормально. Как дальше поступить

2021-12-30 10:28 UTC, akepman commented
Все подправил, прошу проверить. Спасибо.

2022-01-04 10:15 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув!)

2022-01-04 13:46 UTC, merged